<?php
$model = $view->getParam('all');
?>
<table>  
    <thead>
        <tr>
            <th>Код</th> 
            <th>Название</th>    
            <th>Описание</th> 
            <th>Фото</th> 
            <th>Цена</th> 
            <th>Остаток</th> 
        </tr>
    </thead>
    <tbody>
        <?php foreach($model as $value) { ?>
                    <tr>
                        <td><?php echo $value->sku; ?></td>
                        <td><?php echo $value->name; ?></td>
                        <td><?php echo $value->description; ?></td>
                        <td><img class="photo" src="<?php echo $value->photo; ?>" alt="photo"></td>
                        <td><?php echo $value->price; ?></td>
                        <td><?php echo $value->total; ?></td>
                    </tr>
         <?php   } ?>
    </tbody>
</table>
