<form <?php
if ($is_save) {
    echo 'class="hide"';
}
?> name="insert" action="/admin/save/table/<?php echo $table; ?>" enctype="multipart/form-data" method="POST" autocomplete="off">
    <p>
        <?php if($update) echo '<input type="hidden" name="SKU" value="' . $model->sku . '"/><br />';
            else echo '<input placeholder="Код" type="text" name="SKU" maxlength="20" /><br />';
        ?>
        <input placeholder="Название" type="text" name="name" maxlength="20" <?php if($update) echo 'value="' . $model->name . '"'; ?>/><br />
        <input placeholder="Описание" type="text" name="description" maxlength="20" <?php if($update) echo 'value="' . $model->description . '"'; ?>/><br />        
        <input placeholder="Цена" type="text" name="price" maxlength="30" <?php if($update) echo 'value="' . $model->price . '"'; ?>/><br />
        <input placeholder="Остаток" type="text" name="total" maxlength="20" <?php if($update) echo 'value="' . $model->total . '"'; ?>/><br />
        <input type="hidden" name="MAX_FILE_SIZE" value="10000000">
    <div class="file-upload">
        <button type="button">Выбрать</button>
        <div>Файл не выбран</div>
        <input type="file" name="photo">
    </div>
</p>     
<input type="submit" name="<?php if($update) echo 'update'; else echo 'insert'; ?>" value="Сохранить" />
</form>
