<h2>Заказы</h2>
<table>  
    <thead>
        <tr>
            <th>   
                <a class="insert" href="/admin/insert/table/<?php echo $table; ?>">Добавить</a>
                Код заказа
            </th>  
            <th>Код клиента</th>    
            <th>Дата</th> 
            <th>Сумма</th> 
        </tr>
    </thead>
    <tbody>
        <?php foreach ($model as $value) { ?>
            <tr>
                <td><?php echo $value->id; ?></td>
                <td><?php echo $value->user_id; ?></td>
                <td><?php echo $value->date; ?></td>
                <td><?php echo $value->sum; ?></td>
                <td><input type="button" data-id="<?php echo $value->sku; ?>" class="edit" data-table="<?php echo $table; ?>"></td>
                <td><input type="button" data-id="<?php echo $value->sku; ?>" class="delete" data-table="<?php echo $table; ?>"></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
