<?php
$is_save = $view->getParam('is_save');
$error = $view->getParam('error');
$table = $view->getParam('table');
$update = $action == 'updateAction' ? true : false;
?>

<h2>Добавление</h2>
<div class="formwrapper">
    
<?php 
    include $viewNameForm;
?>
    
    <p class="submitInfo"><?php
        if ($is_save) {
            echo 'Сохранено!';
        }
        if ($error) {
            echo $error;
        }
        ?></p>
    <a class="insert <?php
       if (!$is_save) {
           echo 'hide';
       }
        ?>" href="/admin/insert/table/<?php echo $table; ?>">Добавить еще</a>
</div>

