<ul class="adminMenu">
    <li><a href="/admin/user">Клиенты</a></li>
    <li><a href="/admin/product">Товары</a></li>
    <li><a href="/admin/order">Заказы</a></li>
</ul>

<div class="content">
    <h1>Администрирование</h1>
    <h2>Добавление клиента</h2>
    <form name="insert" method="POST" autocomplete="off">
        <p>
            <input placeholder="Имя" type="text" name="first_name" maxlength="20" /><br />
            <input placeholder="Фамилия" type="text" name="last_name" maxlength="20" /><br />
            <input placeholder="Почта" type="text" name="email" maxlength="20" /><br />        
            <input placeholder="Пароль" type="password" name="password" maxlength="30"/><br />
        </p>
        <p>
            <input id="PHP" type="checkbox" name="skills" value="PHP"><label for="PHP">PHP</label>
            <input id="CSS" type="checkbox" name="skills" value="CSS"><label for="CSS">CSS</label>
            <input id="Javascript" type="checkbox" name="skills" value="Javascript"><label for="Javascript">Javascript</label>
            <input id="Java" type="checkbox" name="skills" value="Java"><label for="Java">Java</label>
            <input id="HTML" type="checkbox" name="skills" value="HTML" checked><label for="HTML">HTML</label>
            <input id="Web-design" type="checkbox" name="skills" value="Web-design"><label for="Web-design">Web-design</label>
        </p>
        <p>
            <input id="role2" type="radio" name="role_id" value="2" checked><label for="role2">Простой клиент</label>
            <input id="role5" type="radio" name="role_id" value="5"><label for="role5">Администратор</label>
            <input id="role6" type="radio" name="role_id" value="6"><label for="role6">Продвинутый клиент</label>
            <input id="role7" type="radio" name="role_id" value="7"><label for="role7">Супер клиент</label>
        </p>
        <p>
            <input placeholder="Возраст" type="text" name="year" maxlength="20" /><br />
            <input placeholder="Фото" type="text" name="photo" maxlength="30" /><br />
        </p>     
        <input type="submit" name="insert" value="Сохранить" />
    </form>
    <p class="submitInfo"></p>
    <a class="insert hide" href="/admin/insert">Добавить еще</a>
</div>
