<?php
$is_save = $view->getParam('is_save');
$error = $view->getParam('error');
$model = $view->getParam('model');
$table = $view->getParam('table');
$update = $action == 'updateAction' ? true : false;
?>

<h2>Изменение</h2>
<?php 
    if ($model) : 
        
        include $viewNameTable;

    elseif ($view->getParam('error')) : ?>
    <div class="error"><?php echo $view->getParam('error') ?></div>
<?php endif; ?>

<div class="formwrapper">
    
    <?php 
        include $viewNameForm;
    ?>
    
    <p class="submitInfo"><?php
        if ($is_save) {
            echo 'Сохранено!';
        }
        if ($error) {
            echo $error;
        }
        ?></p>
<!--        <a class="insert <?php //if (!$is_save) { echo 'hide'; }  ?>" href="/admin/insert">Добавить еще</a>-->
</div>


