<?php
/**
 * @var Model
 */
$user = $view->getParam('all');
$table = $view->getParam('table');
?>

<h2>Клиенты</h2>
<?php if ($user) : ?>
    <table>  
        <thead>
            <tr>
                <th>   
                    <a class="insert" href="/admin/insert/table/<?php echo $table; ?>">Добавить</a>Код</th>    
                <th>Имя</th>    
                <th>Фамилия</th>    
                <th>Почта</th> 
                <th>Активность</th> 
                <th>Навыки</th> 
                <th>Роль</th> 
                <th>Возраст</th> 
                <th>Фото</th> 
            </tr>
        </thead>
        <tbody>
            <?php foreach ($user as $value) { ?>
                <tr>
                    <td><?php echo $value->id; ?></td>
                    <td><?php echo $value->name; ?></td>
                    <td><?php echo $value->lastName; ?></td>
                    <td><?php echo $value->email; ?></td>
                    <td><?php echo $value->isActive; ?></td>
                    <td><?php echo $value->skills; ?></td>
                    <td><?php echo $value->role_id; ?></td>
                    <td><?php echo $value->year; ?></td>
                    <td><img class="photo" src="<?php echo $value->photo; ?>" alt="photo"></td>
                    <td><input type="button" data-id="<?php echo $value->id; ?>" class="edit" data-table="<?php echo $table; ?>"></td>
                    <td><input type="button" data-id="<?php echo $value->id; ?>" class="delete" data-table="<?php echo $table; ?>"></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>

<?php elseif ($view->getParam('error')) : ?>
    <div class="error"><h1><?php echo $view->getParam('error') ?></h1></div>
<?php endif; ?>


