<h2>Контакты</h2>
<table>  
    <caption>Dmitry Skriplyonok</caption>
    <tbody>
        <tr>
            <td>Phone</td>
            <td>+38 (097) 365-66-06</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>dimaskriplyonok@mail.ru</td>
        </tr>
        </tr>
        <tr>
            <td>Skype</td>
            <td>dimaskriplyonok@mail.ru</td>
        </tr>
        </tr>
        <tr>
            <td>City</td>
            <td>Kharkiv</td>
        </tr>
    </tbody>
</table>
