<?php
$userId = $controller->getUserId();
$userRoleId = 0;
if ($userId) {
    $userModel = Model_User::getById($userId);
    $userEmail = $userModel->email;
    $userRoleId = $userModel->role_id;
}
?>
<html>
    <head>
        <title>InetShop for programmers</title>
        <link rel="stylesheet" text="text/css" href="/css/style.css?<?php echo time(); ?>">
        <meta charset="utf-8">
        <script type="text/javascript" src="/js/jquery.js"></script>
        <script type="text/javascript" src="/js/authorize.js?<?php echo time(); ?>"></script>
    </head>    
    <body>
        <div class="main-wrapper">
            <header>
                <div class="container">
                    <div class="logo">
                        <a href="/"><span class="mainlogo">InetShop</span><span class="slogan">for programmers</span></a>
                    </div>
                    <menu id="mainmenu">
                        <ul>
                            <li><a href="/">Главная </a></li>
                            <li><a href="/product/select/table/product">Продукты </a></li>
                            <li><a href="/company/about">О компании </a></li>
                            <li><a href="/company/contact">Контакты </a></li>
                            <li>
                                <a id="admin_href" href="/admin/index"
                                <?php
                                if ($userRoleId != Model_User::ROLE_ADMIN) { echo 'class="hide"'; }
                                ?>>Админка</a>
                            </li>
                        </ul>
                    </menu>
                    <div class="authorize">
                        <div id="error"><?php echo !empty($errorMessage) ? $errorMessage : '';       ?></div>
                        <div class="formdata <?php if (empty($userId)) { echo ' hide';} ?>">
                            <div id="userEmail"><?php echo !empty($userId) ? 'Вы зашли как: ' : ''; ?><a href="<?php echo !empty($userId) ? '/user/profile/id/' . $userId : ''; ?>"><?php echo !empty($userEmail) ? $userEmail : ''; ?></a></div>
                            <div id="exit"><a id="logout" href="#"><?php echo !empty($userId) ? 'Выйти' : '' ?></a></div>
                        </div>

                        <div id="loginFormDiv" <?php if (!empty($userId)) { echo 'class="hide"'; } ?>>

                            <form name="autorize" id="loginForm" method="POST" autocomplete="off">
                                <input placeholder="Почта" type="text" name="email" maxlength="20" /><br />
                                <input placeholder="Пароль" type="password" name="password" maxlength="30" /><br />                       
                                <input type="submit" name="login" value="Войти" />
                                <input id="save_checkbox" type="checkbox" name="save" value="1" /><label for="save_checkbox">Запомнить</label><br />
                                <input type="submit" name="register" value="Зарегистрироваться" />
                            </form>
                        </div>
                    </div>
                </div>  
            </header>
            <main class="container">
                <div class="content">
                    <?php
                    if (file_exists($viewNameSection)) {
                        include $viewNameSection;
                    }
                    ?>
                </div>
            </main>
            <footer class="footer">
                <span>&copy; <a href="/">InetShop</a> 2017. All Rights Reserved.</span>
            </footer>
            
            <div class="popup" id="popup">
                <div class="popup-content">
                    <p class="popup-info">Вы уверены?</p>
                    <div>
                        <a class="close insert yes" href="#">Да</a>
                        <a class="close insert ok hide" href="#">Ok</a>
                        <a class="close insert no" href="#">Нет</a>
                    </div>
                </div>
            </div>
            
        </div>
    </body>

</html>